trigger:
  - master

resources:
  containers:
    - container: dockeragent
      image: "827063637024.dkr.ecr.us-east-1.amazonaws.com/docker-registry:35"
      endpoint: "aws_ecr"
container: dockeragent
steps:
- task: ManualValidation@0
  inputs:
    notifyUsers: 'nehakumari971650@gmail.com'
- script: |
    hostname
  displayName: container testing
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

