apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: 049483755852.dkr.ecr.ap-south-1.amazonaws.com/mynodejs-app:14-2020-06-23
        resources:
          limits:
            cpu: "100m"
            memory: "200Mi"
          requests:
            cpu: "100m"
            memory: "200Mi"
        ports:
        - containerPort: 3000

