# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseTag:
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

    # Specify the script here
        
    # Azure CLI version to be used to execute the script. If not provided, latest version is used
#         azcliversion: # optional, default is latest
#       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $GITHUB_REF
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Required, workflow file name or ID
          workflow: main.yml
          # Optional, will get head commit SHA
         # pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
         # commit: 1b27f4116b24b536067d01086ec4aa79b79e459c
          # Optional, will use the branch
          branch: master
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: my-artifact
          # Optional, directory where to extract artifact
          path: ./test
          # Optional, defaults to current repo
          repo: neha9700199/food-site 
      - name: run script
        run: |
          pwd
          ls -ltra
      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install Python depencies with pip
      - name: pip-install-python-dependencies
        run: python -m pip install --upgrade pip setuptools wheel pybump ruamel.yaml pyyaml shyaml
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.0
        env:
          AZURE_DEVOPS_EXT_PAT: 'kt53yidqochaupbsseakpkaj7cj3ufqug2afiunpgkzuqq3rnwoa'
        with:
          inlineScript: |
            az extension add --name azure-devops
            az extension show --name azure-devops
            az devops configure --defaults organization=https://dev.azure.com/kumari8700neha
            echo "kt53yidqochaupbsseakpkaj7cj3ufqug2afiunpgkzuqq3rnwoa" > my_pat_token.txt
            cat my_pat_token.txt
            echo ${{ env.AZURE_DEVOPS_EXT_PAT }} | az devops login --organization https://dev.azure.com/kumari8700neha/
            echo "login is success" 
            az artifacts universal publish --organization https://dev.azure.com/kumari8700neha/ --feed new-feed --name my-first-package --version 0.0.1 --description "Welcome to Universal Packages" --path ./test
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
