# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseTag:
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        git-repo: [spring-boot-dockerize-master, javaProject, food-site]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

    # Specify the script here
        
    # Azure CLI version to be used to execute the script. If not provided, latest version is used
#         azcliversion: # optional, default is latest
#       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $GITHUB_REF
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          branch: master
          name: my-artifact
          path: ./test
          repo: neha9700199/${{ matrix.git-repo }}
      - name: run script
        run: |
          pwd
          ls -ltra
      - name: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: pip-install-python-dependencies
        run: python -m pip install --upgrade pip setuptools wheel pybump ruamel.yaml pyyaml shyaml keyring~=17.1.1
      
