# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      releaseTag:
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

    # Specify the script here
        
    # Azure CLI version to be used to execute the script. If not provided, latest version is used
#         azcliversion: # optional, default is latest
#       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $GITHUB_REF
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token
          github_token: ${{secrets.GITHUB_TOKEN}}
          # Required, workflow file name or ID
          workflow: main.yml
          # Optional, will get head commit SHA
         # pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
         # commit: 1b27f4116b24b536067d01086ec4aa79b79e459c
          # Optional, will use the branch
          branch: main
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: my-artifact
          # Optional, directory where to extract artifact
          path: ./
          # Optional, defaults to current repo
          repo: neha9700199/food-site 
      - name: run script
        run: |
          pwd
          ls -ltra
